### ISSUE TITLE
As a user, I would like to see a higher fidelity image, more images, and interactive things(e.g. twitter feed) when I go to a details page

### ISSUE THREAD

**Issue by JamesCrabtree** [JeffJiang42/idb#48]
Details pages are somewhat barebones with only a single blown-up image and text.  It would be nice to have some things to interact with on the page.

**Comment by JeffJiang42** [comment]
We are unsure how to implement this one. The APIs we are consuming do not provide this data, so we would have to scrape some additional data from other sources and update the database, which might not be able to be done in a week. We are also unsure what we could scrape for additional data that would apply to all model cases. For example, one idea we had was to insert the Wikipedia summary of a subject in the Subjects details page, but some of our subjects are called "Other" and  "Memory and Study Skills," which would not have any meaningful results in Wikipedia.

**Comment by JeffJiang42** [comment]
We are quite limited in the data we can provide, so we will be adding a twitter feed for the providers in each model's details page (e.g. GitHub Jobs for jobs, Khan Academy for courses/subjects)
